### ISSUE TITLE
CRITICAL: 'MULTI_NEIGHBORS'

### ISSUE THREAD

**Issue by randomhammer** [davidlesieur/multi_neighbors#1]
I'm trying to install the plugin and Pelican is spitting out the following when I run `make html`

CRITICAL: 'MULTI_NEIGHBORS'

Other plugins are working just fine, so it's not a path issue. Any idea of where I can start looking for the issue? I'm stumped.

**Comment by davidlesieur** [comment]
The MULTI_NEIGHBORS variable was probably missing from your Pelican settings file. Commit 7a4fdbb230866fc24085c0ef86f813a6d4ecf4a3 should fix this; the plugin now provides a default value.
